Bump version to 1.28.0
Also increase the PrepareRelease timeout

Revert "Revert "Delete old unused pipelines and files (#1513)" (#1588)" (https://github.com/DataDog/dd-trace-dotnet/pull/1595)

This reverts commit 9bdd9d7f29813f09002bd1126e20259ac130bd28.

Fix Linux artifacts (https://github.com/DataDog/dd-trace-dotnet/pull/1587)

* Fix Linux artifacts

* Fix default paths used in build_in_docker.sh

Bitrise spec update. (https://github.com/DataDog/dd-trace-dotnet/pull/1593)

Fix native leak in TypeInfo (https://github.com/DataDog/dd-trace-dotnet/pull/1596)

* Fix native leak in TypeInfo

TypeInfo instance holds 2 pointers but they are never freed
Use std::shared_ptr to automate and simplify the memory management of this type.

* Use std::make_shared instead of split allocating and object creation

Add a custom test framework to monitor execution of unit tests (https://github.com/DataDog/dd-trace-dotnet/pull/1572)

* Add a custom test framework to monitor execution of unit tests
* Enable xunit diagnostic messages

Fix arm64 tar suffix (missing '.') (https://github.com/DataDog/dd-trace-dotnet/pull/1598)

Add a public ForceFlushAsync API on the Tracer (https://github.com/DataDog/dd-trace-dotnet/pull/1599)

Fixes native memory leaks (https://github.com/DataDog/dd-trace-dotnet/pull/1600)

* - Adds a new UniqueBlockingQueue class
- Transform the RejitItem struct to use std::unique_ptr<T>
- Move all implementations from the headers to the cpp file.

* Cleaning and removing more leaks.

* Adding more unique_ptr.

Bump version to 1.28.1-prerelease (https://github.com/DataDog/dd-trace-dotnet/pull/1603)

* Bump version to 1.28.1-prerelease

* Update docs/CHANGELOG.md

Co-authored-by: Tony Redondo <tony.redondo@datadoghq.com>

Co-authored-by: Tony Redondo <tony.redondo@datadoghq.com>

Add code coverage to the consolidated pipeline (https://github.com/DataDog/dd-trace-dotnet/pull/1527)

Update package versions + fix MSTest (https://github.com/DataDog/dd-trace-dotnet/pull/1604)

* Update package versions

* Fix MSTest for version 2.2.5

Previously, we were receiving only one SimpleSkipParameterizedTest because the skip was executed before iterating the parameters. That changed in 2.2.5, so each parameterised run gets a span

Make the benchmark step optional (https://github.com/DataDog/dd-trace-dotnet/pull/1608)

Run the npgsql/npgsql tests in our pipelines with the profiler attached (https://github.com/DataDog/dd-trace-dotnet/pull/1431)

Adds a new Azure DevOps pipeline to run integration tests from libraries, starting with Npgsql
- Runs Npgsql tests at tags v4.1.9 and v5.0.7, on both Ubuntu and Windows, with automatic instrumentation enabled
- Downloads .NET Tracer artifacts from the latest master build that produces the dotnet-tool. This requires changes (done in this PR) to automatically tag builds with the appropriate build tag when they build the dotnet-tool
- Scheduled to run daily at 3am UTC
- Sets up Postgres with several extensions like PostGIS. These setup instructions were copied directly from the source repo

Split Windows regression tests and integration tests to save drive space (https://github.com/DataDog/dd-trace-dotnet/pull/1586)

* Split the regression tests and the integration tests

These test are actually independent (currently) so we can save drive space by splitting them into two jobs, one which builds the regression tests, another which builds the samples.

That saves us ~2GB in both jobs, which should stave off drive space issues for a while

* Update build/_build/Build.cs

Co-authored-by: Zach Montoya <zach.montoya@datadoghq.com>

Co-authored-by: Zach Montoya <zach.montoya@datadoghq.com>

Merge tools into Nuke (https://github.com/DataDog/dd-trace-dotnet/pull/1605)

* Merge GeneratePackageVersions into Nuke

* Move UpdateVendors tool to be a Nuke target

Embed the template as a resource for simplicity

* minor: move Nuke helper files into folder for easier navigation

* Move EnvironmentTools.cs to Datadog.Trace.TestHelpers

It's only used in test projects anyway

* Move TcpPortProvider to TestHelpers, as again, it's only used in tests

Some of the sample projects use this type, so rather than reference TestHelpers (and hence transitively Datadog.Trace), added the helper class a link file instead.

* Remove remaining references to Datadog.Core.Tools

* Move PrepareRelease to Nuke

This required quite a lot of work in the GenerateIntegrationDefinitions code to use reflection instead of direct references.

Additionally, I purposefully iterate all the built versions of the assembly, and de-dupe the duplicates, to avoid cases where some integrations are not available on some platforms. This required a slightly annoying amount of boilerplate and faffing with AppLoadContexts

* Move CIAppTracking project to Nuke

* Don't override everything in Nuke's editorconfig

* Update build/_build/Build.Utilities.cs

Co-authored-by: Zach Montoya <zach.montoya@datadoghq.com>

* Remove DistributedTracer tool

It's for a very specific use-case, and as it's the last remaining tool, I decided to remove it

* Apply suggestions from code review

Co-authored-by: Lucas Pimentel-Ordyna <lucas.pimentel@datadoghq.com>

* Update some target names

Co-authored-by: Zach Montoya <zach.montoya@datadoghq.com>
Co-authored-by: Lucas Pimentel-Ordyna <lucas.pimentel@datadoghq.com>

Add GitHub workflows for automating Release creation (https://github.com/DataDog/dd-trace-dotnet/pull/1611)

This creates 4 new workflows:
* Auto add PR to `vNext` milestone
* Create version bump PR
* Auto tag version bump commit
* Create draft release from latest tag

To make later stages of the release workflow easier, this will automatically run when a pull request is closed, and add it to a `vNext` milestone. Only _merged_ PRs that will be included in the next release should be added to the `vNext` milestone.

When we're ready to do a release, the first step is to do a "version bump" commit. This workflow can be _manually_ triggered from the GitHub actions page, where you provide the next version number, and whether or not it's a prerelease.

The action first updates the changelog, using the titles of all PRs included in the `vNext` milestone, using the existing format.

Next it does the version bump, updates integrations.json, and syncs the MSI contents.

After that's complete it renames the `vNext` milestone to the appropriate value, e.g. `1.28.2-prerelease`.

Finally, it creates a branch called `version-bump-1.28.2-prerelease` (for example), commits the changed files to it, pushes, and opens a PR.

Users can then review the PR, make changes if required, and merge the PR.

When the `[Version Bump]` commit above is merged to master, a new workflow is kicked off, that automatically pushes a new tag, `v1.28.2-prerelease` to the repo. This also creates the benchmark branch (as the previous worklfow was doing)

 ## Create draft release from latest tag

 The final workflow creates the draft release from the latest tag assets. This assumes that you've already done a version bump PR (it doesn't _require_ that it's the auto-bump, it just needs to have an entry in the changelog, and assets in Azure Devops).

 The workflow starts by downloading the assets for the `v1.28.2-prerelease` tag build from Azure Devops. We publish a "well known" artifact that it uses to pull everything down, warning/erroring if it can't find an expected build, if the build isn't complete, or if it failed to produce any assets.

 Once download and extracted, it extracts the release notes from the changelog, and uses these to create a draft release. The release notes include warning/reminders about uploading the nuget packages to nuget, and about attaching the signed MSI artifacts

 Final publishing is up to a user, there's no automation around that

Add analyzer project + ThreadAbortAnlayzer to detect inifinte loops on ThreadAbortException (https://github.com/DataDog/dd-trace-dotnet/pull/1325)

* Add Analyzer project with a ThreadAbortException analyzer

Unit tests confirm the analyzer detects and can fix the issue
The analyzer is designed to catch situation caused by the bug in the runtime https://github.com/dotnet/runtime/issues/9633, triggered by a try catch nested tight in a while loop.

* Add ThreadAbortAnalyzer to all the src libraries

* Remove RESX file - unnecessary complexity as not localizing

* Add missing file headers

* Whitespace changes

Co-authored-by: Lucas Pimentel-Ordyna <lucas.pimentel@datadoghq.com>

* Replace remaining MSTest with XUnit

* Remove boilerplate and use helpers from the package instead

Co-authored-by: Lucas Pimentel-Ordyna <lucas.pimentel@datadoghq.com>

Fix PInvokes to the native lib on non windows os. (https://github.com/DataDog/dd-trace-dotnet/pull/1612)

* Fixes PInvokeMap on non windows platforms.

* Add Call from Initialize method.

* Addressing PR comments

* Changes based in a PR comment.

CIApp - Add support to add custom env-vars from dd-trace wrapper (https://github.com/DataDog/dd-trace-dotnet/pull/1594)

* Add support to add custom env-vars from dd-trace wrapper.

* Update src/Datadog.Trace.Tools.Runner/Utils.cs

Co-authored-by: Andrew Lock <andrew.lock@datadoghq.com>

* Fix compilation errors.

* revert solution

Co-authored-by: Andrew Lock <andrew.lock@datadoghq.com>

Fix CIApp Feature Tracking (https://github.com/DataDog/dd-trace-dotnet/pull/1616)

Fix crank project reference (https://github.com/DataDog/dd-trace-dotnet/pull/1617)

* Fix project reference

* Remove project reference and use reflection instead.

Add fallback for logs injection for NLog versions < 4.1.0 (https://github.com/DataDog/dd-trace-dotnet/pull/1607)

Until NLog 4.1.0, there is only one Set API in the MappedDiagnosticsContext class: Set(string, string). Our new CustomNLogLogProvider requires Set(string, object) API, which was introduced in NLog 4.1.0, to use our optimized LogEnricher type. Without this API present, we can't use our CustomNLogLogProvider type so revise the IsLoggerAvailable check to fail when the API is not found.

Add fix for log injection with log4net.Ext.Json versions < 2.0.9.1 (https://github.com/DataDog/dd-trace-dotnet/pull/1615)

Add fix for log4net.Ext.Json versions < 2.0.9.1 not supporting log4net.Core.IFixingRequired for special-case object rendering.

Background
The log4net.Ext.Json library is a prominent third-party library that can render log4net objects into JSON. To prepare the final JSON object, the StandardTypesDecorator does a type check against each value in the MDC dictionary and tries to render each object accordingly. If the value is a well-known type, then the idiomatic JSON value is written. If not, the decorator will render the value as a new JSON object and attempt to render each of the original object's members as properties on the new JSON object.

Bug
In log4net.Ext.Json versions < 2.0.9.1, the interface log4net.Core.IFixingRequired is not included in the set of types specifically recognized as a built-in type, so the custom object Log4NetEnricher+TracerProperty that we insert into the MDC dictionary is rendered as a new JSON object, not a string, which breaks trace-log correlation.

Fix
Before using our CustomLog4NetLogProvider (which utilizes our Log4NetEnricher for holding the current trace_id and span_id values for logs injection), check if the application is using log4net.Ext.Json version 2.0.9.1 or newer. If not, we'll fallback to the original liblog log provider implementation.

Include the project reference to the crank sample to avoid the error trying to locate the managed assembly. (https://github.com/DataDog/dd-trace-dotnet/pull/1618)

don't include analyzer when publishing projects (https://github.com/DataDog/dd-trace-dotnet/pull/1619)

Fixes the dd-trace exit code always returning 0 (https://github.com/DataDog/dd-trace-dotnet/pull/1621)

* Fixes the dd-trace exit code always returning 0

* Removes exit code 1 on --version

Removes version from the testFramework tag (https://github.com/DataDog/dd-trace-dotnet/pull/1622)

Add ASP.NET Core on IIS Express tests (https://github.com/DataDog/dd-trace-dotnet/pull/1582)

* Convert ASP.NET Core tests to snapshot tests

* Add snapshots for ASP.NET Core tests

* Add tests for middleware-only branches and map branches

* Update snapshots for new branches

* Add CallTarget and RouteTemplateResourceNames tests

* Add snapshots for CallTarget and feature flag for aspnetcore tests

* Add additional IIS app types, instead of just classic/integrated

To support running asp.net core on iis, both in- and out- of process

* Add ASP.NET Core module to applicationHost.config

Add dummy config for aspnetcore module.

* Add web.config to ASP.NET Core apps

* Add ASP.NET Core IIS tests

* Add support for x86 tests

We have to use the x86 version of dotnet.exe, to run in IIS express. So use the x86 version version on Windows when running x86 tests

* Add snapshots for ASP.NET Core IIS tests

* Iis tests aren't supported on Linux

* Fix CallTarget setting.

* Remove incorrect comment

* fixup add additional iis

* Fix rebasing issues

Fix ReJIT and Shutdown log levels. (https://github.com/DataDog/dd-trace-dotnet/pull/1624)

Fix ARM64 Integration tests (https://github.com/DataDog/dd-trace-dotnet/pull/1629)

* Fix ARM64 Integration tests

ARM64 integration tests have not been running due to a typo in the test filter

`Exception filtering tests: Incorrect format for TestCaseFilter Error: Missing ')'. Specify the correct format and try again. Note that the incorrect format can lead to no test getting executed.`

* Add missing ARM64 AWS SQS config to docker-compose

Clear metadata when appdomain unloads (https://github.com/DataDog/dd-trace-dotnet/pull/1630)

Exclude more vendored files from code coverage (https://github.com/DataDog/dd-trace-dotnet/pull/1632)

Add additional scrubbing for stacktraces in snapshots (https://github.com/DataDog/dd-trace-dotnet/pull/1633)

* Stop splitting snapshots by architecture

We only needed to do this for the exception messages, but it's annoying, and will only get worse with NGEN support (as .NET Core 2.1 will have different stack traces, for example)

* Update Snapshots (delete x86 snapshots, rename x64 snapshots)

* Add additional scrubbing to the StackTrace

With this change we only keep (and compare) the first "at " in the stack trace. This ensures consistency across platforms and runtimes.

* Update snapshots with scrubbed stack traces

Logger API refactoring (https://github.com/DataDog/dd-trace-dotnet/pull/1625)

* Move logging free functions (Info, Debug, Warn) to static function member of Logger class
* Rewrite the logger implementation to allow one logger for the Tracer, for the Profiler,
  for the Common librairies, and more...

Preserve the task cancelled state when using calltarget instrumentation (https://github.com/DataDog/dd-trace-dotnet/pull/1634)

Fixes the native logger path issue (https://github.com/DataDog/dd-trace-dotnet/pull/1635)

Enable experimental NGEN support (https://github.com/DataDog/dd-trace-dotnet/pull/1628)

* Initial basic support.

* Finish NGEN experimental support.

* Temporal workaround over RequestReJITWithInliners.

* remove comment.

* Fixes compilation error.

* Refactor and ensure always calling EnqueueForRejit either having complete or incomplete data.

* Add checks.

* update comments.

* Fix ReJIT on NGEN.

* Apply suggestions from code review

Co-authored-by: Lucas Pimentel-Ordyna <lucas.pimentel@datadoghq.com>

* Adaptation to the new loader.

Co-authored-by: Lucas Pimentel-Ordyna <lucas.pimentel@datadoghq.com>

Add additional logs injection fallback for NLog 1.x (https://github.com/DataDog/dd-trace-dotnet/pull/1614)

This work follows from pull request https://github.com/DataDog/dd-trace-dotnet/pull/1607

The previous PR fixes NLog logs injection to work correctly when applications use NLog versions >= 2.0. This PR provides an additional fix for NLog logs injection to work correctly when applications use NLog versions >= 1.0. This is accomplished by adding a new NLog log provider that extends the built-in LibLog NLogLogProvider by also searching for the `NLog.MDC` type for the `Set`/`Remove` APIs which exists in NLog 1.x, in addition to `NLog.MappedDiagnosticsContext` which only exists in NLog 2.x and later.